"""empty message

Revision ID: 0808ee67c664
Revises: 
Create Date: 2019-03-09 22:53:41.527861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0808ee67c664'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiller_transaction',
    sa.Column('transaction_id', sa.String(length=24), nullable=False),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('trans_description', sa.String(length=125), nullable=True),
    sa.Column('short_description', sa.String(length=100), nullable=True),
    sa.Column('full_description', sa.String(length=225), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('category_hint', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=25), nullable=True),
    sa.Column('account_num', sa.String(length=10), nullable=True),
    sa.Column('institution', sa.String(length=20), nullable=True),
    sa.Column('dateadded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiller_transaction')
    # ### end Alembic commands ###
